# update all packages, unless marked with "pyup: ignore" in the requirements file
update: all

# enabling version pinning
pin: True

branch: develop

# automatically discover requirements files
search: True
