# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-20 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_address', models.CharField(max_length=100)),
                ('sender_name', models.CharField(blank=True, default='', max_length=100)),
                ('receiver_name', models.CharField(blank=True, default='', max_length=100)),
                ('receiver_address', models.CharField(max_length=100)),
                ('mail_subject', models.CharField(max_length=100)),
                ('mail_body', models.TextField()),
                ('sent', models.BooleanField(default=False)),
                ('delivered', models.BooleanField(default=False)),
                ('read', models.BooleanField(default=False)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_sent', models.DateTimeField(blank=True)),
                ('time_delivered', models.DateTimeField(blank=True)),
                ('time_read', models.DateTimeField(blank=True)),
            ],
            options={
                'ordering': ('time_created',),
            },
        ),
    ]
